version: '3'
services:

  web:
    container_name: beacon
    build:
      context: dist/beacon/
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    links:
      - redis
      - db
    depends_on:
      - redis
      - db

  redis:
    container_name: beacon-redis
    image: "redis:alpine"
  db:
    container_name: beacon-db
    build:
      context: dist/sql/
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 123456
